language: objective-c

before_install: 
- export LANG=en_US.UTF-8
- gem install cocoapods
- brew update
- brew upgrade xctool

script: 
- xctool clean build test -workspace JSMessagesDemo.xcworkspace -scheme JSMessagesDemo -sdk iphonesimulator6.0 ONLY_ACTIVE_ARCH=NO
