platform :ios, '7.1'
pod 'Parse-iOS-SDK'
pod 'libextobjc/EXTScope'
#pod 'JSQSystemSoundPlayer'
#pod 'Reveal-iOS-SDK'
#pod 'SSKeychain'
pod 'AFNetworking'
#pod 'Parse+NSCoding', '~> 0.1.4'
#pod 'TNSexyImageUploadProgress', '~> 0.2'
pod 'TestFlightSDK'
pod 'SDWebImage'
#pod 'XCDYouTubeKit'
#pod 'LiveFrost'
#pod 'SDURLCache'
#pod 'TTTAttributedLabel'
#pod 'HTStateAwareRasterImageView'
#pod 'iCarousel'
#pod 'FontAwesomeKit/FontAwesome'

#pod 'SKBounceAnimation'
#pod 'SHOmniAuthTwitter'
#pod 'PBJVideoPlayer'
#pod 'PBJVision'
#pod 'SHEmailValidator'
